---
title: "Ch. 5"
author: "Danielle Lawrence"
date: "9/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(nycflights13)
library(tidyverse)
```


```{r}
View(flights)
```

Filter allows to subset observations based on their values
have to use ==


5.2.4
1. 
```{r}
filter(flights, arr_delay >= 120) #had delay 2hr or more
```

```{r}
filter(flights, dest == "IAH" | dest == "HOU")
```

```{r}
filter(flights, carrier == "AA" | carrier == "DL" | carrier == "UA")
```

```{r}
filter(flights, month %in% 7:9)
```

```{r}
filter(flights, arr_delay > 120, dep_delay <= 0)
```

```{r}
filter(flights, dep_delay >= 60, dep_delay - arr_delay > 30)
```

```{r}
summary(flights$dep_time)
filter(flights, dep_time <= 600 | dep_time == 2400)
```

2. 
```{r}
filter(flights, between(month, 7, 9))
```

3.
```{r}
filter(flights, is.na(dep_time))
```

4. ???


Arrange changes order of rows

5.3.1
1. 
```{r}
arrange(flights, desc(is.na(dep_time)), dep_time)
```

2.
```{r}
arrange(flights, desc(dep_delay)) #latest
arrange(flights, dep_delay) #earliest
```

3.
```{r}
fastest_flights <- mutate(flights, mph = distance/air_time * 60)
head(arrange(fastest_flights, desc(mph)))
```

4.
```{r}
arrange(flights, desc(distance))
arrange(flights, distance)
```


5.4.1
1.
```{r}
select(flights, dep_time, dep_delay, arr_time, arr_delay)
select(flights, "dep_time", "dep_delay", "arr_time", "arr_delay")
```

2.
```{r}
select(flights, year, month, day, day, year)
```

3.
```{r}
vars <- c("year", "month", "day", "dep_delay", "arr_delay")
select(flights, one_of(vars))
```

4.
```{r}
select(flights, contains("TIME")) #contains ignores caps
```


5.5.2
1.



5.6.7
1.The worst is arrival delay. 

2.
```{r}
not_cancelled <- flights %>%
  filter(!is.na(dep_delay), !is.na(arr_delay))
not_cancelled %>%
  group_by(tailnum) %>%
  tally()
```

3. Most important column is arr_delay because it wont arrive if it never leaves.

4. 
```{r}
cancelled_per_day <-
  flights %>%
  mutate(cancelled = (is.na(arr_delay) | is.na(dep_delay))) %>%
  group_by(year, month, day) %>%
  summarise(
    cancelled_num = sum(cancelled),
    flights_num = n(),
  )
```
```{r}
ggplot(cancelled_per_day) +
  geom_point(aes(x = flights_num, y = cancelled_num))

```

positive relationship 


5. 
```{r}
flights %>%
  group_by(carrier) %>%
  summarise(arr_delay = mean(arr_delay, na.rm = TRUE)) %>%
  arrange(desc(arr_delay))
```

6. Used to sort results, also can be used with arrange.


5.7.1
1.
2.
```{r}
flights %>%
  filter(!is.na(tailnum)) %>%
  mutate(on_time = !is.na(arr_time) & (arr_delay <= 0)) %>%
  group_by(tailnum) %>%
  summarise(on_time = mean(on_time), n = n()) %>%
  filter(min_rank(on_time) == 1)
```

3.
```{r}
flights %>%
  group_by(hour) %>%
  summarise(arr_delay = mean(arr_delay, na.rm = TRUE)) %>%
  arrange(arr_delay)
```





